//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrudApp
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Drawing;
    using System.Drawing.Imaging;
    using System.Web;

    public partial class Student
    {
        public int StudentID { get; set; }

        [Required]
        [StringLength(20)]
        public string StudentName { get; set; }

        [Required]
        [StringLength(12)]
        public string RegistrationNo { get; set; }

        [Required]
        [StringLength(30)]
        public string Address { get; set; }

        [Required]
        public int ProvinceID { get; set; }

        [Required]
        public int CityID { get; set; }

        [Required]
        [EmailAddress]
        public string Email { get; set; }

        //[Required]
        //[RegularExpression(@"^.*\.(jpg|JPG|gif|jpeg|png)$", ErrorMessage = "sad" /*ErrorMessage = "Only image files allowed. "*/)]
        public string Picture { get; set; }

        public HttpPostedFileBase ImageFile { get; set; }

        public virtual City City { get; set; }

        public virtual Province Province { get; set; }
    }
}